/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package struct;

public class App {
    /*
    * 처음 만들어줌
    */
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
