/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package struct

import spock.lang.Specification

class AppTest extends Specification {
    def "초기 앱 테스트"() {
        setup:
        def app = new App()

        when:
        def result = app.greeting

        then:
        result != null
    }
}
